/**:
  ros__parameters:
    joy_type: DS4
    update_rate: 10.0
    accel_ratio: 1.5
    brake_ratio: 2.5
    steer_ratio: 0.3
    steering_angle_velocity: 0.1
    accel_sensitivity: 0.5
    brake_sensitivity: 0.5
    control_command:
      raw_control: false
      velocity_gain: 0.5
      max_forward_velocity: 0.56
      max_backward_velocity: 0.5
      backward_accel_ratio: 1.0
